# Generated by Django 5.1.1 on 2025-06-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(default='Shop', max_length=100)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('site_name', models.CharField(default='shop E-Commerce', max_length=200)),
                ('company_name', models.CharField(default='shop Technologies', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Information',
                'verbose_name_plural': 'Site Information',
            },
        ),
    ]
