# Generated by Django 5.1.1 on 2025-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='trasnjection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
