# Generated by Django 5.1.1 on 2025-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_orderplaced_trasnjection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trasnjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=100)),
            ],
        ),
    ]
