# Generated by Django 5.1.1 on 2025-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_trasnjection'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
