# Generated by Django 5.1.1 on 2025-06-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_orderplaced_date_orderplaced_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
