# Generated by Django 5.1.1 on 2025-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_cart_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
