# Generated by Django 5.1.1 on 2025-11-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
